# Generated by Django 4.2.14 on 2024-07-12 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookCollection", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Todo",
            new_name="BookCollection",
        ),
    ]
